/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health/checks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Checks */
        get: operations["health_checks_health_checks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Chat */
        post: operations["chat_chat_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Conversations */
        get: operations["list_conversations_conversations_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations/{conversation_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Conversation */
        get: operations["open_conversation_conversations__conversation_id__get"];
        put?: never;
        post?: never;
        /** Delete Conversation */
        delete: operations["delete_conversation_conversations__conversation_id__delete"];
        options?: never;
        head?: never;
        /** Rename Conversation */
        patch: operations["rename_conversation_conversations__conversation_id__patch"];
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Jobs
         * @description Newest first. Repeat `state` to filter, e.g. `?state=queued&state=running`.
         */
        get: operations["list_jobs_jobs_get"];
        put?: never;
        /** Start Job */
        post: operations["start_job_jobs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Job */
        get: operations["get_job_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{job_id}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Cancel Job
         * @description A queued job is cancelled at once; a running job stops at its next check (cancel_requested).
         */
        post: operations["cancel_job_jobs__job_id__cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Folders */
        get: operations["list_folders_folders_get"];
        put?: never;
        /**
         * Add Folder
         * @description Adds a folder to index. 422 with the reason if it doesn't exist, is a system, privacy or
         *     ignored folder, or is already covered by another indexed folder.
         */
        post: operations["add_folder_folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Folder
         * @description Removes the folder from the list; a background job then removes its files from the index.
         */
        delete: operations["remove_folder_folders__folder_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger Ingest */
        post: operations["trigger_ingest_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ingest Status
         * @description The most recent ingestion job, or null if indexing has never run.
         */
        get: operations["ingest_status_ingest_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search */
        get: operations["search_search_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Files */
        get: operations["list_files_files_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/move": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Move */
        post: operations["move_files_move_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/files/organize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Organize */
        post: operations["organize_files_organize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_projects_get"];
        put?: never;
        /**
         * Create Project
         * @description Creates a project without folders. 409 if another project has the same name, ignoring case.
         */
        post: operations["create_project_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open Project */
        get: operations["open_project_projects__project_id__get"];
        put?: never;
        post?: never;
        /**
         * Delete Project
         * @description Deletes the project, its folder list and its chats. Files in its folders are never touched.
         */
        delete: operations["delete_project_projects__project_id__delete"];
        options?: never;
        head?: never;
        /**
         * Update Project
         * @description Renames the project or edits its instructions; fields left out are kept.
         */
        patch: operations["update_project_projects__project_id__patch"];
        trace?: never;
    };
    "/projects/{project_id}/folders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Add Project Folder
         * @description Adds a folder. 422 with the reason if it doesn't exist, is a system, privacy or ignored folder,
         *     or is already in the project.
         */
        post: operations["add_project_folder_projects__project_id__folders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{project_id}/folders/{folder_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove Project Folder
         * @description Takes the folder off the project. Its files are never touched.
         */
        delete: operations["remove_project_folder_projects__project_id__folders__folder_id__delete"];
        options?: never;
        head?: never;
        /** Set Folder Permission */
        patch: operations["set_folder_permission_projects__project_id__folders__folder_id__patch"];
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Liveness only, without the token, so Electron can wait for the server. Details: GET /health/checks.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddFolderRequest */
        AddFolderRequest: {
            /**
             * Path
             * @description Full path of an existing folder.
             */
            path: string;
        };
        /** AddProjectFolderRequest */
        AddProjectFolderRequest: {
            /**
             * Path
             * @description Full path of an existing folder.
             */
            path: string;
            /**
             * Permission
             * @default read
             * @enum {string}
             */
            permission: "read" | "act";
        };
        /** ChatRequest */
        ChatRequest: {
            /** Message */
            message: string;
            /**
             * Use Docs
             * @default false
             */
            use_docs: boolean;
            /** Project */
            project?: string | null;
            /** Conversation Id */
            conversation_id?: string | null;
        };
        /** ChatResponse */
        ChatResponse: {
            /** Response */
            response: string;
            /** Sources */
            sources: string[];
            /** Conversation Id */
            conversation_id: string;
        };
        /** ConversationDetail */
        ConversationDetail: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Started At */
            started_at: string;
            /**
             * Updated At
             * @description Time of the newest message; the list is sorted by this, newest first.
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
            /** Messages */
            messages: components["schemas"]["StoredMessage"][];
        };
        /** ConversationSummary */
        ConversationSummary: {
            /** Id */
            id: string;
            /** Title */
            title: string | null;
            /** Started At */
            started_at: string;
            /**
             * Updated At
             * @description Time of the newest message; the list is sorted by this, newest first.
             */
            updated_at: string;
            /** Message Count */
            message_count: number;
        };
        /** CreateProjectRequest */
        CreateProjectRequest: {
            /** Name */
            name: string;
            /**
             * Instructions
             * @description Instructions the assistant follows in this project's chats.
             * @default
             */
            instructions: string;
        };
        /** FolderPermissionRequest */
        FolderPermissionRequest: {
            /**
             * Permission
             * @enum {string}
             */
            permission: "read" | "act";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthCheck */
        HealthCheck: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "error" | "unknown";
            /** Title */
            title: string;
            /** Detail */
            detail?: string | null;
            /** Fix */
            fix?: string | null;
        };
        /** HealthReport */
        HealthReport: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "warning" | "error";
            /** Checks */
            checks: components["schemas"]["HealthCheck"][];
        };
        /** IndexedFolder */
        IndexedFolder: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /** Added At */
            added_at: string;
        };
        /** Job */
        Job: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Project */
            project: string;
            /**
             * State
             * @enum {string}
             */
            state: "queued" | "running" | "done" | "failed" | "cancelled";
            /** Params */
            params: {
                [key: string]: unknown;
            };
            /**
             * Result
             * @default null
             */
            result: unknown;
            /**
             * Error
             * @default null
             */
            error: string | null;
            /**
             * Progress Current
             * @default null
             */
            progress_current: number | null;
            /**
             * Progress Total
             * @description Unknown while null; the client shows no percentage then.
             * @default null
             */
            progress_total: number | null;
            /**
             * Progress Message
             * @default null
             */
            progress_message: string | null;
            /**
             * Cancel Requested
             * @description A running job stops at its next cancellation check.
             */
            cancel_requested: boolean;
            /** Created At */
            created_at: string;
            /**
             * Started At
             * @default null
             */
            started_at: string | null;
            /**
             * Finished At
             * @default null
             */
            finished_at: string | null;
        };
        /** MoveFileRequest */
        MoveFileRequest: {
            /** Src */
            src: string;
            /** Dst */
            dst: string;
        };
        /** OrganizeRequest */
        OrganizeRequest: {
            /** Folder */
            folder: string;
        };
        /** Project */
        Project: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Instructions */
            instructions: string;
            /** Created At */
            created_at: string;
            /** Folders */
            folders: components["schemas"]["ProjectFolder"][];
        };
        /** ProjectFolder */
        ProjectFolder: {
            /** Id */
            id: number;
            /** Path */
            path: string;
            /**
             * Permission
             * @description read: the assistant may search the folder. act: its tools may also change files there.
             * @enum {string}
             */
            permission: "read" | "act";
            /** Added At */
            added_at: string;
        };
        /** ProjectSummary */
        ProjectSummary: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Instructions */
            instructions: string;
            /** Created At */
            created_at: string;
        };
        /** RenameRequest */
        RenameRequest: {
            /** Title */
            title: string;
        };
        /** StartJobRequest */
        StartJobRequest: {
            /** Kind */
            kind: string;
            /** Params */
            params?: {
                [key: string]: unknown;
            };
            /**
             * Project
             * @default default
             */
            project: string;
        };
        /** StoredMessage */
        StoredMessage: {
            /** Id */
            id: number;
            /**
             * Role
             * @enum {string}
             */
            role: "user" | "assistant" | "tool";
            /** Content */
            content: string;
            /** Sources */
            sources: string[];
            /**
             * Status
             * @description streaming: the reply is still being written. incomplete: it was cut off by an error, Stop or a crash.
             * @enum {string}
             */
            status: "streaming" | "complete" | "incomplete";
            /** Created At */
            created_at: string;
        };
        /** UpdateProjectRequest */
        UpdateProjectRequest: {
            /** Name */
            name?: string | null;
            /** Instructions */
            instructions?: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /**
         * ActionResultEvent
         * @description Not sent yet. The outcome of a file action.
         */
        ActionResultEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "action_result";
            /**
             * Id
             * @default null
             */
            id: string | null;
            /** Tool */
            tool: string;
            /** Success */
            success: boolean;
            /** Text */
            text: string;
        };
        /**
         * ActivityEvent
         * @description Not sent yet. What the assistant is doing, for example running a tool.
         */
        ActivityEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "activity";
            /** Text */
            text: string;
            /**
             * Tool
             * @default null
             */
            tool: string | null;
        };
        /**
         * ApprovalNeededEvent
         * @description Not sent yet. A file action is waiting for the user's approval.
         */
        ApprovalNeededEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "approval_needed";
            /** Id */
            id: string;
            /** Tool */
            tool: string;
            /** Arguments */
            arguments: {
                [key: string]: unknown;
            };
            /** Summary */
            summary: string;
        };
        /**
         * DoneEvent
         * @description The answer is complete. Send conversation_id with the next message to continue the chat.
         */
        DoneEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "done";
            /** Conversation Id */
            conversation_id: string | null;
        };
        /**
         * ErrorEvent
         * @description The request failed. No done event follows, and the server closes the socket.
         */
        ErrorEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "error";
            /** Text */
            text: string;
        };
        /**
         * SourcesEvent
         * @description The documents the answer was based on. Sent once, just before done; may be empty.
         */
        SourcesEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "sources";
            /** Sources */
            sources: string[];
        };
        /**
         * TokenEvent
         * @description The next piece of the answer text. Append it to the text received so far.
         */
        TokenEvent: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "token";
            /** Text */
            text: string;
        };
        ChatEvent: components["schemas"]["TokenEvent"] | components["schemas"]["ActivityEvent"] | components["schemas"]["SourcesEvent"] | components["schemas"]["ApprovalNeededEvent"] | components["schemas"]["ActionResultEvent"] | components["schemas"]["ErrorEvent"] | components["schemas"]["DoneEvent"];
        /**
         * ChatStreamRequest
         * @description The one message the client sends after connecting.
         */
        ChatStreamRequest: {
            /** Message */
            message: string;
            /**
             * Conversation Id
             * @default null
             */
            conversation_id: string | null;
            /**
             * Use Docs
             * @description Defaults to true, except for greetings.
             * @default null
             */
            use_docs: boolean | null;
            /**
             * Project
             * @default null
             */
            project: string | null;
        };
        /**
         * JobEvent
         * @description A job was queued, made progress or finished. Carries the whole job.
         */
        JobEvent: {
            /**
             * Type
             * @default job
             * @constant
             */
            type: "job";
            job: components["schemas"]["Job"];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_checks_health_checks_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthReport"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    chat_chat_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChatResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_conversations_conversations_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_conversation_conversations__conversation_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationDetail"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_conversation_conversations__conversation_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    rename_conversation_conversations__conversation_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                conversation_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RenameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConversationSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_jobs_jobs_get: {
        parameters: {
            query?: {
                state?: ("queued" | "running" | "done" | "failed" | "cancelled")[] | null;
                limit?: number;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_job_jobs_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartJobRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_job_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_jobs__job_id__cancel_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_folders_folders_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexedFolder"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_folder_folders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IndexedFolder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_folder_folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trigger_ingest_ingest_post: {
        parameters: {
            query?: {
                full_reset?: boolean;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ingest_status_ingest_status_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Job"] | null;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_search_get: {
        parameters: {
            query: {
                q: string;
                k?: number;
                project?: string | null;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_files_files_get: {
        parameters: {
            query?: {
                path?: string;
            };
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    move_files_move_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MoveFileRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    organize_files_organize_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrganizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_projects_projects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_projects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    open_project_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProjectRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_project_folder_projects__project_id__folders_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddProjectFolderRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFolder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_project_folder_projects__project_id__folders__folder_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_folder_permission_projects__project_id__folders__folder_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string;
            };
            path: {
                project_id: string;
                folder_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FolderPermissionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectFolder"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
}
